src/Entity/Food.php
<?php

/*
Food entity.
Please change fields according to needs. These fields were generated 
with reference to the Menustat food database.
*/

namespace App\Entity;

use App\Repository\FoodRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FoodRepository::class)]
class Food
{
    // id of food object
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    // Date when food object created
    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTime $Date = null;

    // Name of food object
    #[ORM\Column(type: Types::TEXT)]
    private ?string $FoodName;

    // Restaurant of food, if present
    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $Restaurant = null;

    // Food category (breakfast, lunch, dinner, snack, etc)
    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $FoodCategory = null;

    // Serving size of the food
    #[ORM\Column(nullable: true)]
    private ?float $ServingSize = null;

    // Serving size unit of food
    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $ServingSizeUnit = null;

    // Amount of energy of the food (ie, in kcal)
    #[ORM\Column(nullable: true)]
    private ?float $EnergyAmount = null;

    // Unit for energy of food (ie, kcal)
    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $EnergyUnit = null;

    // Fat amount of food
    #[ORM\Column(nullable: true)]
    private ?float $FatAmount = null;

    // Fat unit of food (ie, gram)
    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $FatUnit= null;

    // Carb amount of food
    #[ORM\Column(nullable: true)]
    private ?float $CarbAmount = null;

    // Carb unit of food (ie, gram)
    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $CarbUnit = null;

    // Protein amount of food
    #[ORM\Column(nullable: true)]
    private ?float $ProteinAmount = null;

    // Protein unit of food (ie, gram)
    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $ProteinUnit = null;

    // User who saved food
    #[ORM\ManyToOne(inversedBy: 'food', cascade: ['persist'])]
    private ?User $User = null;

    // Quantity of food (ie, at 1.5 1gram servings of yogurt)
    #[ORM\Column(nullable:true)]
    private ?float $Quantity = null;

    #[ORM\Column(length: 255,nullable:true)]
    private ?string $DataType = null;

    // Data id (the ID of the food from the database we are pulling from.
    // For instance, this would be the id of the food from the Menustat database,
    // if we were to use that.)
    #[ORM\Column(nullable:true)]
    private ?int $DataId = null;

    #[ORM\Column(nullable: true)]
    private ?float $PotassiumAmount = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $PotassiumUnit = null;

    #[ORM\Column(nullable: true)]
    private ?float $FiberAmount = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $FiberUnit = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $ImagePath = null;

    #[ORM\Column(nullable: true)]
    private ?float $TotalEnergyAmount = null;

    #[ORM\Column(nullable: true)]
    private ?float $TotalFiberAmount = null;

    #[ORM\Column(nullable: true)]
    private ?float $TotalPotassiumAmount = null;

    #[ORM\Column(nullable: true)]
    private ?float $TotalFatAmount = null;

    #[ORM\Column(nullable: true)]
    private ?float $TotalCarbAmount = null;

    #[ORM\Column(nullable: true)]
    private ?float $TotalProteinAmount = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFoodName(): ?string
    {
        return $this->FoodName;
    }

    public function setFoodName(string $name): self
    {
        $this->FoodName = $name;

        return $this;
    }

    public function getRestaurant(): ?string
    {
        return $this->Restaurant;
    }

    public function setRestaurant(?string $Restaurant): self
    {
        $this->Restaurant = $Restaurant;

        return $this;
    }

    public function getFoodCategory(): ?string
    {
        return $this->FoodCategory;
    }

    public function setFoodCategory(?string $FoodCategory): self
    {
        $this->FoodCategory = $FoodCategory;

        return $this;
    }

    public function getServingSize(): ?float
    {
        return $this->ServingSize;
    }

    public function setServingSize(?float $ServingSize): self
    {
        $this->ServingSize = $ServingSize;

        return $this;
    }

    public function getServingSizeUnit(): ?string
    {
        return $this->ServingSizeUnit;
    }

    public function setServingSizeUnit(?string $ServingSizeUnit): self
    {
        $this->ServingSizeUnit = $ServingSizeUnit;

        return $this;
    }

    public function getEnergyAmount(): ?float
    {
        return $this->EnergyAmount;
    }

    public function setEnergyAmount(?float $EnergyAmount): self
    {
        $this->EnergyAmount = $EnergyAmount;

        return $this;
    }

    public function getEnergyUnit(): ?string
    {
        return $this->EnergyUnit;
    }

    public function setEnergyUnit(?string $EnergyUnit): self
    {
        $this->EnergyUnit = $EnergyUnit;

        return $this;
    }

    public function getFatAmount(): ?float
    {
        return $this->FatAmount;
    }

    public function setFatAmount(?float $FatAmount): self
    {
        $this->FatAmount = $FatAmount;

        return $this;
    }

    public function getFatUnit(): ?string
    {
        return $this->FatUnit;
    }

    public function setFatUnit(?string $FatUnit): self
    {
        $this->FatUnit = $FatUnit;

        return $this;
    }

    public function getCarbAmount(): ?float
    {
        return $this->CarbAmount;
    }

    public function setCarbAmount(?float $CarbAmount): self
    {
        $this->CarbAmount = $CarbAmount;

        return $this;
    }

    public function getCarbUnit(): ?string
    {
        return $this->CarbUnit;
    }

    public function setCarbUnit(?string $CarbUnit): self
    {
        $this->CarbUnit = $CarbUnit;

        return $this;
    }

    public function getProteinAmount(): ?float
    {
        return $this->ProteinAmount;
    }

    public function setProteinAmount(?float $ProteinAmount): self
    {
        $this->ProteinAmount = $ProteinAmount;

        return $this;
    }

    public function getProteinUnit(): ?string
    {
        return $this->ProteinUnit;
    }

    public function setProteinUnit(?string $ProteinUnit): self
    {
        $this->ProteinUnit = $ProteinUnit;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getQuantity(): ?float
    {
        return $this->Quantity;
    }

    public function setQuantity(float $Quantity): self
    {
        $this->Quantity = $Quantity;

        return $this;
    }

    public function getDataType(): ?string
    {
        return $this->DataType;
    }

    public function setDataType(string $DataType): self
    {
        $this->DataType = $DataType;

        return $this;
    }

    public function getDataId(): ?int
    {
        return $this->DataId;
    }

    public function setDataId(int $DataId): self
    {
        $this->DataId = $DataId;

        return $this;
    }
    public function getDate(): ?\DateTime
    {
        return $this->Date;
    }
    public function setDate(?\DateTime $Date): self
    {
        $this->Date = $Date;
        return $this;
    }

    public function getPotassiumAmount(): ?float
    {
        return $this->PotassiumAmount;
    }

    public function setPotassiumAmount(?float $PotassiumAmount): self
    {
        $this->PotassiumAmount = $PotassiumAmount;

        return $this;
    }

    public function getPotassiumUnit(): ?string
    {
        return $this->PotassiumUnit;
    }

    public function setPotassiumUnit(?string $PotassiumUnit): self
    {
        $this->PotassiumUnit = $PotassiumUnit;

        return $this;
    }

    public function getFiberAmount(): ?float
    {
        return $this->FiberAmount;
    }

    public function setFiberAmount(?float $FiberAmount): self
    {
        $this->FiberAmount = $FiberAmount;

        return $this;
    }

    public function getFiberUnit(): ?string
    {
        return $this->FiberUnit;
    }

    public function setFiberUnit(?string $FiberUnit): self
    {
        $this->FiberUnit = $FiberUnit;

        return $this;
    }

    public function getImagePath(): ?string
    {
        return $this->ImagePath;
    }

    public function setImagePath(?string $ImagePath): self
    {
        $this->ImagePath = $ImagePath;

        return $this;
    }

    public function getTotalEnergyAmount(): ?float
    {
        return $this->TotalEnergyAmount;
    }

    public function setTotalEnergyAmount(?float $TotalEnergyAmount): self
    {
        $this->TotalEnergyAmount = $TotalEnergyAmount;

        return $this;
    }

    public function getTotalFiberAmount(): ?float
    {
        return $this->TotalFiberAmount;
    }

    public function setTotalFiberAmount(?float $TotalFiberAmount): self
    {
        $this->TotalFiberAmount = $TotalFiberAmount;

        return $this;
    }

    public function getTotalPotassiumAmount(): ?float
    {
        return $this->TotalPotassiumAmount;
    }

    public function setTotalPotassiumAmount(?float $TotalPotassiumAmount): self
    {
        $this->TotalPotassiumAmount = $TotalPotassiumAmount;

        return $this;
    }

    public function getTotalFatAmount(): ?float
    {
        return $this->TotalFatAmount;
    }

    public function setTotalFatAmount(?float $TotalFatAmount): self
    {
        $this->TotalFatAmount = $TotalFatAmount;

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
        <!-- jquery -->
        <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
        {# Boxicons #}
        <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {# Unicons #}
            <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
            {# Custom styles #}
            <link rel="stylesheet" href = "{{asset('build/app.css')}}">
        {% endblock %}
    </head>
    <nav class="navbar navbar-dark bg-dark navbar-expand-lg">
        <img src="{{asset('images/uofsc_logo.png')}}" alt="UofSC Logo"
        width="50rem" height="50rem"
        >
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-3">
            {% if app.user %}
                {% if is_granted('ROLE_ADMIN') %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{{path('admin')}}">
                        <i class="uil uil-cog"></i>
                        Admin
                        </a>
                    </li>
                {% endif %}
                <li class="nav-item active">
                    <a class="nav-link" href="/">
                    <i class="uil uil-estate"></i>
                    Home 
                    </a>
                </li>
                <li class = "nav-item active">
                    <a class = "nav-link" href = "/food">
                        <i class="uil uil-pizza-slice"></i>
                        Food
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/about">
                        <i class="uil uil-subject"></i>
                        About
                    </a>
                </li>
                <li class = "nav-item">
                    <a class="nav-link" href = "/user/pie_charts">
                    <i class="uil uil-bolt"></i>
                    Dashboard
                    </a>
                </li>
            {% endif %}
            
            {% if not app.user %}
            <li class="nav-item">
                <a class="nav-link" href="/register">
                <i class="uil uil-pen"></i>
                Register
                </a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="/{{app.user ? 'logout':'login'}}"
                @click="isOpen = false"
                >
                {{app.user ? '
                <i class="uil uil-signout"></i>
                Logout
                ':'
                <i class="uil uil-signin"></i>
                Login'}}
                </a>
            </li>
            </ul>
        </div>
    </nav>
    <br>

    <body class = "">
        {% block body %}{% endblock %}
    </body>

    {% block footer %}
        <footer class = "container">
            Copyright 2022 University of South Carolina.
        </footer>
    {% endblock footer %}

    {% block javascript %}
        {{encore_entry_script_tags('app')}}
    {% endblock %}
</html>

templates/index.html.twig
{% extends "base.html.twig" %}

{% block title %}
Welcome
{% endblock title %}

{% block body %}
<h1 class = 'text-center'>
    Home
</h1>



<div>
</div>
{% endblock body %}